### ISSUE TITLE
Makes config group and world readable

### ISSUE THREAD

**Issue by jlaw90** [vvbogdanov87/gnome-shell-extension-kubeconfig#11]
I just noticed is that this modifies the permissions of the config file when switching contexts.  Ideally it should not modify this attribute at all.

**Comment by jesseops** [comment]
I've run into the same issue; as a workaround I use `setfacl` to enforce the appropriate permissions:

```bash
setfacl -d -m u::rwX,g::-,o::- ~/.kube
```

Hope this is helpful to others running into the same issue.

**Comment by adrianlyjak** [comment]
thanks @jesseops! just what I needed
