### ISSUE TITLE
compatible for 40.0.0 Gnome version

### ISSUE THREAD

**Issue by yrsurya** [vvbogdanov87/gnome-shell-extension-kubeconfig#13]
This tool helps great while having multi cluster . It would be nice if this can be updated to use in 40.0.0 Gnome version of Fedora34

**Comment by chrisleekr** [comment]
I agree. This extension was one of the best extensions that I am using daily.

**Comment by vvbogdanov87** [comment]
The new version is available at `extensions.gnome.org`

**Comment by smazurov** [comment]
Seems like it still shows as incompatible on Gnome 40, Fedora 34:

![image](https://user-images.githubusercontent.com/21636/121722040-2b020f00-caa2-11eb-8211-81ac0af4b695.png)
