### ISSUE TITLE
ReferenceError: TextDecoder is not defined

### ISSUE THREAD

**Issue by jt55401** [vvbogdanov87/gnome-shell-extension-kubeconfig#20]
After upgrade today, no longer switches contexts. Log entry is:

Dec 08 17:33:16 pop-os gnome-shell[27850]: gnome-shell-extension-kubeconfig, ReferenceError: TextDecoder is not defined

I'm on
`Linux pop-os 5.15.5-76051505-generic #202111250933~1638201579~21.10~09f1aa7 SMP Mon Nov 29 16:23:13 U x86_64 x86_64 x86_64 GNU/Linux
gnome-shell    40.5-1ubuntu2pop0~1633630918~21.10~91d3049 amd64`

let me know if you need any other details

**Comment by vvbogdanov87** [comment]
@jt55401 I deactivated bugged version on the extensions site and uploaded the new one. It will be available as soon as it passes the gnome team review.

Please confirm the issue is resolved. I tested it on Ubuntu 21.10 gnome 40.5. For the details see PR #21

**Comment by jt55401** [comment]
Confirmed, after update, it works again, thanks!
