### ISSUE TITLE
Support to Gnome 42

### ISSUE THREAD

**Issue by daneebrand** [vvbogdanov87/gnome-shell-extension-kubeconfig#23]
Hi, 

I couldn't create a branch.

I fixed the extension code to gnome 42

# metadata.json

    "shell-version": [
        "40",
        "41",
        "42"
    ]

# kubeIndicator.js

from: 

const KubeIndicator = GObject.registerClass ({GTypeName: 'KubeIndicator'},
    class KubeIndicator extends PanelMenu.Button {
    ...
    }
    
to: 

var KubeIndicator = GObject.registerClass ({GTypeName: 'KubeIndicator'},
    class KubeIndicator extends PanelMenu.Button {
    ....
    }
    
# kubePopupMenuItem.js

from: 

const KubePopupMenuItem = GObject.registerClass ({GTypeName: 'KubePopupMenuItem'},
    class extends PopupMenu.PopupBaseMenuItem {
    ... 
    }

to: 
var KubePopupMenuItem = GObject.registerClass ({GTypeName: 'KubePopupMenuItem'},
    class extends PopupMenu.PopupBaseMenuItem {
     ....
     }

**Comment by vvbogdanov87** [comment]
Hi, you need to fork the repo, create a branch in the fork and submit the PR. Here is a pretty good guide on how to contribute on github https://akrabat.com/the-beginners-guide-to-contributing-to-a-github-project/

**Comment by daneebrand** [comment]
Hi, Thanks.

I opened a PR.

Your extension is essenstial for my day work :)

**Comment by fadam-csgroup** [comment]
Fixed in https://github.com/vvbogdanov87/gnome-shell-extension-kubeconfig/pull/24
